### ISSUE TITLE
Try a different license?

### ISSUE THREAD

**Issue by aaronliu0130** [Floorp-Projects/Floorp-private-components#1]
[Creative commons recommends against using itself for software.](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) Using a copyleft license like the GPL3 forces bad forks to also release their source code and declare their changes. If you'd really like to prohibit commercial use, there's https://directory.fsf.org/wiki/License:UnivUtahRFPL.

**Comment by Ryosuke-Asano** [comment]
I want this CC license to be temporary.

I welcome discussion on this. I'm not a licensing expert so please give me some information

**Comment by aaronliu0130** [comment]
The first link should explain why CC shouldn't be used for code. The Utah and GPL solve these problems, and the latter permits selling, but only under the condition that the seller also open sources their code.

Another reason to choose the GPL is that the FSF provides free lawyers to sue violations for you.

**Comment by Ryosuke-Asano** [comment]
GPL I'm not going to choose at the moment, so I'll look at the former

**Comment by aaronliu0130** [comment]
Another NC code license is https://directory.fsf.org/wiki/License:Commons-Clause. It's also license-agnostic.

**Comment by aaronliu0130** [comment]
Microsoft also has their https://directory.fsf.org/wiki/License:Ms-SS license, which is NC and can probably be used after replacing mentions of "Microsoft". I don't see the "permits commercial use under certain circumstances" the FSF purports.

**Comment by dominichayesferen** [comment]
> [Creative commons recommends against using itself for software.](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) Using a copyleft license like the GPL3 forces bad forks to also release their source code and declare their changes. If you'd really like to prohibit commercial use, there's https://directory.fsf.org/wiki/License:UnivUtahRFPL.

On an unrelated note, it's weird - AppStream, and Flatpak, recognise CC licenses as valid licenses for applications to use, despite this.

**Comment by aaronliu0130** [comment]
No matter [how horrible your license is](https://www.gnu.org/licenses/license-list.en.html#JSON), it is always a "valid" choice. FlatHub's only requirement seems to be that you can redistribute it.

**Comment by xiota** [comment]
Older versions of these files were already released under another open source license.  Changing license could prompt forks simply because of the license change (eg, iceweasel, icecat, librewolf, etc).  It's a huge mess when that happens.

**Comment by aaronliu0130** [comment]
1. This was previously licensed under MPL anyway
2. CC is a very uncontroversially bad code license, and I don't see why we should be afraid of forks

**Comment by Ryosuke-Asano** [comment]
I do not intend to loosen the license any further.

I've compromised a lot just by releasing the source code, so I'll delete the sentence asking for a looser license, since it's not relevant to the discussion.

**Comment by aaronliu0130** [comment]
Erm, I think there was a problem in translation :) My reply did not ask for a looser license, but only said that 1. Switching from CC to another license (which doesn't have to be looser; it can be the Microsoft license I mentioned above which has the same requirements), would not be controversial since CC is bad for code 2. The code was previously licensed under MPL anyway (not saying that we should switch back to it)

<details>
<summary>願わくば正しい機械翻訳を</summary>
ええと、翻訳に問題があるようです :) 私の返事は、よりゆるいライセンスを求めたのではなく、次のように言ったのだ。

1. CCから他のライセンス（これはより緩いライセンスである必要はなく、私が上で述べたマイクロソフトのライセンスでもよい）に切り替えることは議論の余地がない。

2. コードはすでにMPLから変更されている（MPLに戻すべきだとは言っていない）。
</details>

**Comment by Ryosuke-Asano** [comment]
> Erm, I think there was a problem in translation :) My reply did not ask for a looser license, but only said that 1. Switching from CC to another license (which doesn't have to be looser; it can be the Microsoft license I mentioned above which has the same requirements), would not be controversial since CC is bad for code 2. The code was previously licensed under MPL anyway (not saying that we should switch back to it)
> 願わくば正しい機械翻訳を
> ええと、翻訳に問題があったようです :) 私の返事は、より緩いライセンスを求めたのではなく、1. CCから他のライセンス（より緩いライセンスである必要はなく、私が上で述べたMicrosoftのライセンスであってもよい。）2. このコードは以前MPLでライセンスされていた（MPLに戻すべきだとは言っていない）。

Sorry, I wake up now. My thinking was not good now.

**Comment by Ryosuke-Asano** [comment]
Ok. I remove CC LICENSE from this repository.
