### ISSUE TITLE
Merge back with main repo?

### ISSUE THREAD

**Issue by xiota** [Floorp-Projects/Floorp-private-components#2]
1. This repo is now misnamed (no longer "private").
2. If code is public, why not merge back with the main repo with LICENSE info included in the directory?
    * Simplifies building.
    * No more "Update submodule" commits with no information about what was actually updated.

**Comment by Ryosuke-Asano** [comment]
Thanks for the advice!

But I will not do this yet as at the moment I am still exploring licenses!

**Comment by Ryosuke-Asano** [comment]
I considering about this merge
