### ISSUE TITLE
Floorp toolbar colorization bug +suggestion of fix

### ISSUE THREAD

**Issue by AChPCoder** [Floorp-Projects/Floorp-private-components#3]
Floorp allows enable wonderful feature named "Use favicon color for tab panel background".
But while i'm using that with vertical tabs, these panel background isn't changed and color is changed. Site with black favicon on light bg makes white text (white text on white bg), and with white favicon makes dark text on dark background.

That can be because while vertical tabs enabled, there isn't shares them bgcolor with `#navigator-toolbox` element.

Code, which set these css values is here: [https://github.com/Floorp-Projects/Floorp-private-components/blob/48e31b842a0a552e43b01828b1411bb0d77bada9/browser/base/content/browser-favicon-color.js#L118](https://github.com/Floorp-Projects/Floorp-private-components/blob/48e31b842a0a552e43b01828b1411bb0d77bada9/browser/base/content/browser-favicon-color.js#L118)
My suggestion: pass these colors as css variables on highest parent element of browser DOM (like html or :root or body), then use these vars in any necessary styles.
It's can be look like:
```
:root {
    --floorp-tab-panel-bg-color: ${result.averageColor};
    --floorp-tab-panel-fg-color: ${textColor};
}

#navigator-toolbox:not(:-moz-lwtheme),
#navigator-toolbox:-moz-lwtheme {
    background-color: var(--floorp-tab-panel-bg-color) !important;
}

.tab-label:not([selected="true"]) {
    color: var(--floorp-tab-panel-fg-color) !important;
}

.tab-icon-stack>*,
#TabsToolbar-customization-target>*,
#tabs-newtab-button,
.titlebar-color>* {
    color: var(--floorp-tab-panel-fg-color) !important;
    fill: var(--floorp-tab-panel-fg-color) !important;
}
```
Thanks in advance for your attention to that message.

**Comment by Ryosuke-Asano** [comment]
Ok. Wait a moment.

**Comment by Ryosuke-Asano** [comment]
Could you send a PR?
